import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><link rel="apple-touch-icon" href="/apple-touch-icon.png" /></head><body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="app-layout-wrapper">
          <Navigation />
          <div className="app-layout-main">
            {children}
          </div>
        </div>
        <style>{`
          .app-layout-wrapper {
            display: flex;
            min-height: 100vh;
          }
          .app-layout-main {
            flex: 1;
            min-width: 0;
            padding-bottom: 72px;
          }
          @media (min-width: 769px) {
            .app-layout-main {
              margin-left: 200px;
              padding-bottom: 0;
            }
          }
        `}</style>
      </body>
    </html>
  );
}
